name: novatech
description: "A new Flutter project."

publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1 # or latest
  permission_handler: ^11.0.1
  intl: ^0.19.0
#
#fonts:
#  - family: Roboto
#    fonts:
#      - asset: fonts/Roboto-Regular.ttf
#      - asset: fonts/Roboto-Bold.ttf
#        weight: 700

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.10
  url_launcher: ^6.2.5
  image_picker: ^1.0.4
  permission_handler: ^11.3.0
  firebase_core: ^3.5.0
  firebase_auth: ^5.2.0
  path_provider: ^2.1.3
  http: ^1.2.1
  geolocator: ^11.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/page1.jpg
    - assets/page2.jpg
    - assets/page3.jpg
    - assets/india_flag.jpg
    - assets/Splash_screen.jpg
    - assets/map_icon.jpg
    - assets/handshake.jpg
    - assets/profile_sample.jpg
    - assets/dummy.jpg

flutter_native_splash:
  color: "#6A4D90"
  image: assets/Splash_screen.png  # ✅ FIXED: Same as above
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
